name: safety_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.17
  flutter_phone_direct_caller: ^2.1.0
  flutter_sms: ^2.3.2
  geolocator: ^9.0.1
  http: ^0.13.4
  provider: ^6.0.1
  geocoding: ^2.0.1
  sqflite: ^2.0.1
  path: ^1.8.0
  flutter_spinkit: ^5.1.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.2
  cloud_firestore: ^3.1.5
  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.12
  introduction_screen: ^2.1.0
  cool_alert: ^1.1.0
  spring: ^2.0.2
  toggle_switch: ^1.4.0
  another_flushbar: ^1.10.28
  location: ^4.2.0
  fluttertoast: ^8.0.8
  telephony: ^0.2.0
  timer_snackbar: ^0.0.3
  google_maps_flutter: ^2.1.1
  lottie: ^1.3.0
  share_plus: ^4.0.4
  shake: ^2.1.0
  sizer:
  permission_handler: ^10.0.0
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/homeScreen/
    - assets/images/peopleScreen/
    - assets/images/onboardingScreen/
    - assets/images/splashScreen/
    - assets/images/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700